version: 2.1

jobs:
  build:
    machine: true  # should default to Ubuntu 22.04, as of May 19, 2022
    resource_class: medium
    steps:
      - run:
          name: verify OS
          command: |
            lsb_release -a
      - run:
          name: update apt and install tools
          command: |
            # try sudo
            sudo apt-get update
            sudo apt-get install -y mysql-client
            
            which mysql
      
